global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "code-review-assistant"
    static_configs:
      - targets: ["app:9090"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "code-review-metrics"
    static_configs:
      - targets: ["app:9090"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "^code_review_.*"
        action: keep

rule_files:
  # - "alert_rules.yml"

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
